### ISSUE TITLE
Please update for SAMD Micro-controllers

### ISSUE THREAD

**Issue by RubenFixit** [mpflaga/Arduino_Library-vs1053_for_SdFat#12]
Currently only AVR micro-controllers are supported. I feel like very little effort should be needed by someone familiar with the code to make the changes necessary to support other architectures.

**Comment by mpflaga** [comment]
Yes, that may now be the case. I would evaluate any requested push that provided a solution for reproducible environment as to sustain QA. When started there were not that many SAMD systems. Nor do I have any such at present. This is more a feature request, rather than a bug fix.

Thanks for your input.
