### ISSUE TITLE
Nano to OTS Module Jumpers?

### ISSUE THREAD

**Issue by johnyradio** [mpflaga/Arduino_Library-vs1053_for_SdFat#5]
Hi

Can you recommend jumpers for the Nano to an off-the-shelf (OTS) VS1053 module? Plus needed code changes?

My **VS1053 module** has the following pinouts:
5V
GND
CS
MISO
SI
SCK
XCS
XRESET
XDCS
DREQ

Here are the Nano pinouts:

![Pinout-NANOevery_v1](https://user-images.githubusercontent.com/6564280/71300081-c3548300-2346-11ea-976e-45ec8770cf71.png)

**Comment by mpflaga** [comment]
Please refer to 
[User Guide](http://mpflaga.github.io/Sparkfun-MP3-Player-Shield-Arduino-Library/)
and
[config.h](https://github.com/mpflaga/Arduino_Library-vs1053_for_SdFat/blob/master/src/vs1053_SdFat_config.h#L210
)
These documents provide explanations of specific use cases. Specifically the config.h has a section that maps out PIN numbers of specific pin functions. So that you can map a solution. 

If you have not already, given this is very late.
